function plot_data_bnd(geom, data, width, marker, size)

assert(geom.is_2d==true, 'invalid geom');

for i=1:length(geom.line)
    x = geom.line{i}.x;
    y = geom.line{i}.y;
    v = data(geom.line{i}.idx);

    surface(...
        'XData',[x(:) x(:)],...
        'YData',[y(:) y(:)],...
        'ZData',zeros(length(data.line{i}),2),...
        'CData',[v(:) v(:)], ...
        'FaceColor','none',...
        'EdgeColor','flat',...
        'LineStyle','-',...
        'LineWidth', width, ...
        'Marker', marker,...
        'MarkerSize', size,...
        'MarkerFaceColor', 'auto',...
        'MarkerEdgeColor', 'auto');
    hold('on')
end

end