function plot_mesh_bnd(geom, color, width, marker, size)

assert(geom.is_2d==true, 'invalid geom');

for i=1:length(geom.line)
    x = geom.line{i}.x;
    y = geom.line{i}.y;

    plot(...
        x, y,...
        'Color', color,...
        'LineStyle','-',...
        'LineWidth', width, ...
        'Marker', marker,...
        'MarkerSize', size,...
        'MarkerFaceColor', color,...
        'MarkerEdgeColor', color);
    hold('on')
end

end